local GuiLib = require "guilib.guilib"
local dropdown_component = require "components.dropdown.dropdown"


local examples = {
  ["Pressed/Hold/Released"] = require("examples.pressed_hold_released.pressed_hold_released"),
  Hover = require("examples.hover.hover"),
  -- Action = require("examples.action.action"),
  -- ["Enter/Leave"] = require("examples.enter_leave.enter_leave"),
  -- ["Click Outside"] = require("examples.click_outside.click_outside"),
  -- ["Emit Action"] = require("examples.emit_action.emit_action"),
  -- ["Components: Dragable"] = require("examples.components.dragable.dragable"),
  -- ["Components: Slider"] = require("examples.components.slider.slider"),
  ["Components: Panel"] = require("examples.components.panel.panel")
}

local current_example = nil

local log_text_list = {}
local log_counter = 0
local log_previous_text = nil
local function log(text)
  if log_previous_text == text then
    log_counter = log_counter + 1
    log_text_list[1] = string.format("%s (%d)", text, log_counter)
  else
    log_counter = 1
    log_previous_text = text
    table.insert(log_text_list, 1, text)
    if #log_text_list>10 then
      log_text_list[#log_text_list] = nil
    end
  end
  gui.set_text(gui.get_node("logtext"), table.concat(log_text_list, "\n"))
end

local function log_clear()
  gui.set_text(gui.get_node("logtext"), "")
  log_text_list = {}
end

---@param guilib GuiLib
local function open_example(guilib, name)
  if current_example then gui.set_enabled(current_example, false) end
  current_example = gui.get_node(name .. "/root")
  gui.set_enabled(current_example, true)
  examples[name](guilib, name, log)
  log_clear()
end

function init(self)
  local version = gui.get_node('version')
  gui.set_text(version, string.format(gui.get_text(version), sys.get_config_string("project.version")))
  msg.post(".", "acquire_input_focus")
  self.guilib = GuiLib()
  local dropdown = dropdown_component(self.guilib, "dropdown")
  --
  dropdown.add("Pressed/Hold/Released")
  dropdown.add("Hover")
  -- dropdown.add("Action")
  -- dropdown.add("Enter/Leave")
  -- dropdown.add("Click Outside")
  -- dropdown.add("Emit Action")
  -- dropdown.add("Components: Dragable")
  -- dropdown.add("Components: Slider")
  dropdown.add("Components: Panel")
  --
  dropdown.on_select(function(selection) open_example(self.guilib, selection) end)
  dropdown.set_selected("Pressed/Hold/Released")
  open_example(self.guilib, "Pressed/Hold/Released")
end

function on_input(self, action_id, action)
  self.guilib.on_input(action_id, action)
end
